services:
  db:
    image: mysql
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sergipe-vagas
    volumes:
      - ~/datadir:/var/lib/mysql
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - api-network

  api:
    build: "./"
    container_name: sergipe-vagas_api
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    restart: always
    ports:
      - "8080:8080"
    networks:
      - api-network
    depends_on:
      db:
        condition: service_healthy

networks:
  api-network:
    driver: bridge



