services:
  db:
    image: mysql
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sergipe-vagas
    volumes:
      - ~/datadir:/var/lib/mysql
    restart: always
    networks:
      - api-network

  api:
    build: "./"
    container_name: sergipe-vagas_api
    environment:
      - DB_HOST=db
    restart: always
    ports:
      - "8080:8080"
    networks:
      - api-network
    depends_on:
      - db

networks:
  api-network:
    driver: bridge



